# Generated by Django 4.2.2 on 2023-06-16 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulariocontacto',
            options={'permissions': [('puede_ver_usuarios', 'Permiso para ver usuarios'), ('puede_ver_pagina', 'Permiso para ver pagina')]},
        ),
    ]
